dist: trusty
sudo: require
addons:
  apt:
    packages:
      - "python3.5"
      - "python3.5-pip"
python:
  - 3.5.3
install:
  - sudo pip3 install numpy
  - sudo pip3 install biopython
  - sudo pip3 install nose
script:
  - python3.5 -c "import nose; print(nose.__version__)"
  - python3.5 -m "nose"
notifications:
  email: false