dist: trusty
sudo: require
language: python
python:
  - 3.6
script:
  - source ~/virtualenv/python3.6/bin/activate
  - python --version
  - sudo pip install numpy
  - sudo pip install biopython
  - sudo pip install pytest
  - (cd gramtools/ && python -m pytest)
notifications:
  email: false