dist: trusty
sudo: require
script:
  - source ~/virtualenv/python3.6/bin/activate
  - python --version
  - sudo pip install numpy
  - sudo pip install biopython
  - sudo pip install pytest
  - (cd gramtools/ && python -m pytest)
notifications:
  email: false