dist: trusty
sudo: require
python:
  - 3.6
install:
  - sudo pip install numpy
  - sudo pip install biopython
  - sudo pip install pytest
script:
  - (cd gramtools/ && python3.6 -m pytest)
notifications:
  email: false