dist: trusty
sudo: require
python:
  - 3.6
install:
  - sudo pip3.6 install numpy
  - sudo pip3.6 install biopython
  - sudo pip3.6 install pytest
script:
  - (cd gramtools/ && python3.6 -m pytest)
notifications:
  email: false