dist: trusty
sudo: require
addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
python:
  - 3.5
install:
  - sudo pip3 install numpy
  - sudo pip3 install biopython
  - sudo pip3 install pytest
script:
  - (cd gramtools/ && python3 -m pytest)
notifications:
  email: false